name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libjson-c-dev mingw-w64

      - name: Build Linux binary
        run: make

      - name: Build Windows binary (cross-compile)
        run: |
          make \
            CC=x86_64-w64-mingw32-gcc \
            LDFLAGS="-ljson-c" \
            EXE_SUFFIX=.exe \
            TARGET=trainer

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            trainer
            trainer.exe
